/* Plain-language glossary for Phase 0. Every term is searchable (Ctrl/Cmd+K). */
export const glossary = [
  ['Client', 'The program that asks. A browser, a mobile app, Postman, curl, or even another server.'],
  ['Server', 'A program that waits for requests and answers them. "Server" can also mean the computer it runs on.'],
  ['API', 'Application Programming Interface: a fixed set of "doors" (endpoints) a program opens so other programs can ask it for data or actions.'],
  ['REST', 'REpresentational State Transfer: the common style for web APIs. Resources are nouns in the path (`/events/12`), the HTTP method is the verb, status codes report the result, and each request stands alone.'],
  ['Resource', 'A thing an API lets you work with, such as an event or a user. Each resource has its own address, e.g. `/events/12`.'],
  ['Endpoint', 'One door of an API: a method plus a path, for example `GET /events/12`.'],
  ['Request', 'The message a client sends: method, path, headers and (sometimes) a body.'],
  ['Response', 'The message the server sends back: status code, headers and (usually) a body.'],
  ['HTTP', 'HyperText Transfer Protocol: the agreed rules for how clients and servers talk on the web.'],
  ['HTTPS', 'HTTP inside an encrypted tunnel (TLS). Nobody in between can read or change the messages.'],
  ['TLS', 'Transport Layer Security: the technology that encrypts HTTPS traffic and proves the server is who it claims to be.'],
  ['Certificate', 'A digital ID card for a website, signed by a trusted Certificate Authority. The browser checks it before trusting HTTPS.'],
  ['IP address', 'A computer\'s number on a network, like a phone number. Example: `142.250.183.14`.'],
  ['IPv4 / IPv6', 'Two formats of IP address. IPv4 looks like `93.184.216.34`; IPv6 is longer, like `2606:2800:220:1::`.'],
  ['localhost', 'A name that always means "this same computer". Its IP is `127.0.0.1`.'],
  ['Domain name', 'A human-friendly name for a server, like `api.github.com`. Easier to remember than an IP.'],
  ['DNS', 'Domain Name System: the internet\'s phonebook that turns a domain name into an IP address.'],
  ['DNS resolver', 'The helper (from your ISP, or public ones like 1.1.1.1 and 8.8.8.8) that does the DNS lookup for you.'],
  ['TTL', 'Time To Live: how long a DNS answer may be cached before it must be looked up again.'],
  ['Port', 'A numbered door on a computer that leads to one program. Web servers use 80 (HTTP) and 443 (HTTPS).'],
  ['URL', 'Uniform Resource Locator: the full address of something on the web, e.g. `https://api.site.com/events?sort=date`.'],
  ['Scheme (protocol)', 'The first part of a URL (`http` or `https`). It says which rules to use.'],
  ['Path', 'The part of a URL after the domain that says which resource you want, e.g. `/events/12`.'],
  ['Query string', 'Extra options after `?` in a URL, as `key=value` pairs joined by `&`, e.g. `?sort=date&page=2`.'],
  ['Fragment', 'The part after `#` in a URL. It is used only by the browser and is never sent to the server.'],
  ['HTTP method', 'The verb of a request: GET (read), POST (create), PUT/PATCH (update), DELETE (remove).'],
  ['Header', 'A labelled piece of extra information on a request or response, like `Content-Type: application/json`.'],
  ['Body', 'The main data carried by a request or response, often JSON.'],
  ['Status code', 'A three-digit number in every response that says how it went: 2xx success, 4xx client mistake, 5xx server problem.'],
  ['JSON', 'JavaScript Object Notation: the common text format for sending data between programs, built from `{}` objects and `[]` arrays.'],
  ['Content-Type', 'The header that says what format the body is in, e.g. `application/json` or `text/html`.'],
  ['Stateless', 'Each request stands alone. The server does not remember earlier requests unless the client sends proof again.'],
  ['Cookie', 'A small piece of data the server asks the browser to store and send back automatically on every request to that site.'],
  ['Token', 'A string the client sends (usually in the `Authorization` header) to prove who it is on each request.'],
  ['Idempotent', 'Doing the same request once or ten times leaves the same end result. GET, PUT and DELETE are; POST is not.'],
  ['Frontend', 'The part users see and touch: a website or app running in the browser or on a phone.'],
  ['Backend', 'The part running on a server: business rules, security checks and talking to the database.'],
  ['Database', 'Where data is stored permanently. Only the backend talks to it, never the user directly.'],
  ['TCP', 'Transmission Control Protocol: sets up a reliable connection so data arrives complete and in order. HTTP/1.1 and HTTP/2 run on top of it.'],
  ['Postman', 'A desktop app for sending HTTP requests by hand and seeing the raw response. Great for testing APIs.'],
  ['curl', 'A command-line tool for sending HTTP requests from the terminal.'],
  ['DevTools', 'The browser\'s built-in developer tools. The Network tab lists every request a page makes.'],
];
