/* Plain-language glossary for Phase 1. Every term is searchable (Ctrl/Cmd+K). */
export const glossary = [
  ['Node.js', 'A **runtime** that runs JavaScript outside the browser: V8 to run the code, libuv for waiting on files and the network, plus built-in modules like `fs` and `http`.'],
  ['V8', 'The JavaScript engine from Google Chrome. It turns JavaScript into machine code. Node uses it too.'],
  ['libuv', 'The part of Node that does the waiting: the event loop, timers, files and network connections.'],
  ['REPL', 'Read–Eval–Print Loop. Type `node` with no file to get a prompt where each line runs immediately.'],
  ['const / let', '`const` names can’t be pointed at a new value; `let` names can. Both only exist inside their `{ }` block.'],
  ['Arrow function', 'A short function: `(a, b) => a + b`. With one expression it returns it automatically.'],
  ['Callback', 'A function you pass to other code so it can call it later, e.g. when a timer ends or a request arrives.'],
  ['Execution context', 'The box JavaScript creates to run code: its memory (variables) and the code being run. Each function call gets a new one.'],
  ['Call stack', 'The pile of execution contexts currently running. A call pushes one on top; `return` pops it off. Only the top one runs.'],
  ['Reference', 'For objects and arrays, a variable holds an address, not the object itself. Two variables can point at the same object.'],
  ['Spread', '`...` copies the fields of an object or the items of an array into a new one: `{ ...event, price: 0 }`.'],
  ['Destructuring', 'Pulling values out into names: `const { id } = req.params`, `const [first] = list`.'],
  ['Optional chaining', '`a?.b` gives `undefined` instead of crashing when `a` is null or undefined.'],
  ['Nullish coalescing', '`a ?? b` uses `b` only when `a` is `null` or `undefined` (unlike `||`, it keeps 0 and \'\').'],
  ['Module', 'A file that shares code with `export` and uses others’ code with `import`.'],
  ['Synchronous', 'Runs line by line; each line finishes before the next starts.'],
  ['Asynchronous', 'Starts slow work (a timer, a request, a file read) and carries on; the result is handled later.'],
  ['Blocking', 'Code that keeps the one JavaScript thread busy (like a long loop), so nothing else can run until it finishes.'],
  ['Event loop', 'Node’s scheduler. When the call stack is empty, it runs all microtasks, then takes the next task from the queue.'],
  ['Task queue', 'Where ready callbacks from timers and I/O wait for the call stack to be empty. Also called the callback or macrotask queue.'],
  ['Microtask queue', 'A higher-priority queue for promise callbacks and code after `await`. Emptied completely before the next task.'],
  ['Promise', 'An object for a value that isn’t ready yet. It is **pending**, then settles once as **fulfilled** (a value) or **rejected** (an error).'],
  ['async / await', '`async` marks a function that returns a promise; `await` pauses that function until a promise settles, without blocking anything else.'],
  ['Promise.all', 'Starts waiting on several promises at once and fulfils when all do. Rejects as soon as any one rejects.'],
  ['Unhandled rejection', 'A rejected promise that nothing catches. Modern Node exits the process when it happens.'],
  ['fetch', 'Built-in function to make HTTP requests. Resolves with a response even for 404/500; check `res.ok`.'],
  ['npm', 'Node Package Manager: the command-line tool and the online registry of JavaScript packages.'],
  ['package.json', 'Your project’s ID card: name, `type`, scripts and the ranges of packages it depends on.'],
  ['package-lock.json', 'Records the **exact** version of every installed package so every machine gets identical code. Commit it.'],
  ['node_modules', 'The folder where installed packages live. Huge and rebuildable, so it is never committed.'],
  ['Dependency', 'A package your project needs to run (`dependencies`) or only while developing (`devDependencies`).'],
  ['Semantic versioning', 'MAJOR.MINOR.PATCH: breaking changes, new features, bug fixes. `^1.11.23` allows any newer 1.x.'],
  ['npx', 'Runs a package’s command without installing it globally, e.g. `npx prettier --write .`.'],
  ['Environment variable', 'A setting given to a program from outside the code, like `PORT` or `DATABASE_URL`. Read with `process.env`.'],
  ['.env file', 'A local file of environment variables loaded with `node --env-file=.env`. Contains secrets, so it is never committed.'],
  ['Git', 'A version-control tool on your laptop that saves snapshots (commits) of your project and its history.'],
  ['GitHub', 'A website that hosts Git repositories online for backup, sharing and teamwork.'],
  ['Repository', 'A project folder tracked by Git, including its full history (the hidden `.git` folder).'],
  ['Staging area', 'The list of changes chosen with `git add` for the next commit.'],
  ['Commit', 'A saved snapshot of the staged changes, with a message and a unique ID.'],
  ['Remote', 'A copy of the repository somewhere else, usually GitHub. `origin` is the usual name.'],
  ['.gitignore', 'A file listing paths Git must never track, like `node_modules/` and `.env`.'],
  ['node:http', 'Node’s built-in module for making HTTP servers (and clients) without any framework.'],
  ['Route', 'The code that handles one method + path, e.g. `GET /events/:id`.'],
  ['Stream', 'Data that arrives (or is sent) in chunks over time instead of all at once, like a request body.'],
  ['Express', 'The most popular Node web framework. It adds routing, middleware, body parsing and helpers on top of `node:http`. Phase 2.'],
];
